quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5433/postgres
    password: postgres
    username: postgres

    
  hibernate-orm:
    database:
      generation: none
      #generation: drop-and-create